config/routes.rb
Rails.application.routes.draw do
  devise_for :merchants, :path_prefix => 'auth'
  resources :merchants
  root to: 'merchants#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  store_accessor :extra, :phone_number, :website

  validates :email, format: URI::MailTo::EMAIL_REGEXP

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include PgSearch::Model
  pg_search_scope :search_name, against: :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_merchant!
  add_flash_types :warning
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: %i[ show edit update destroy ]

  # GET /merchants or /merchants.json
  def index
    unless params[:name_filter].blank?
      @merchants = Merchant.search_name params[:name_filter]
    else
      @merchants = Merchant.all
    end
    flash[:info] = "Signed in successfully."
  end

  # GET /merchants/1 or /merchants/1.json
  def show
  end

  # GET /merchants/new
  def new
    if current_merchant.role != 1
      redirect_to merchants_url, warning: "Don't have permissions"
    else
      @merchant = Merchant.new
    end

  end

  # GET /merchants/1/edit
  def edit
    if current_merchant.role != 1
      redirect_to merchants_url, warning: "Don't have permissions"
    end
  end

  # POST /merchants or /merchants.json
  def create
    if current_merchant.role == 1
      @merchant = Merchant.new(merchant_params)
      respond_to do |format|
        if @merchant.save
          format.html { redirect_to @merchant, notice: "Merchant was successfully created." }
          format.json { render :show, status: :created, location: @merchant }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @merchant.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to merchants_url, warning: "Don't have permissions"
    end
  end

  # PATCH/PUT /merchants/1 or /merchants/1.json
  def update
    if current_merchant.role == 1
      respond_to do |format|
        if @merchant.update_without_password(merchant_params)
          format.html { redirect_to @merchant, notice: "Merchant was successfully updated." }
          format.json { render :show, status: :ok, location: @merchant }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @merchant.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to merchants_url, warning: "Don't have permissions"
    end
  end

  # DELETE /merchants/1 or /merchants/1.json
  def destroy
    if current_merchant.role == 1
      @merchant.destroy
      respond_to do |format|
        format.html { redirect_to merchants_url, notice: "Merchant was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to merchants_url, warning: "Don't have permissions"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def merchant_params
      params.require(:merchant).permit(:email, :name, :city, :street, :country_code, :extra, :phone_number, :website, :role, :password)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  private
  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Merchants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br>
  <div class="signed-as">
    <% if current_merchant %>
      Signed in as: <%= current_merchant.email %>.
      <%= link_to 'Sign Out', destroy_merchant_session_path, :method => :delete  %>
    <% end %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/merchants/_form.html.erb
<div class="form-container">
  <%= form_with(model: merchant) do |form| %>
    <% if merchant.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

        <ul>
          <% merchant.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <%= form.text_field :password %>
    </div>

    <div class="field">
      <%= form.label :city %>
      <%= form.text_field :city %>
    </div>

    <div class="field">
      <%= form.label :street %>
      <%= form.text_field :street %>
    </div>

    <div class="field">
      <%= form.label :country_code %>
      <%= form.country_select :country_code %>
    </div>

    <div class="field">
      <%= form.label :role %>
      <%= form.select :role, options_for_select([["Admin role", 1], [ "Viewer role", 0 ] ], merchant.role) %>
    </div>

    <div class="field">
      <%= form.label :phone_number %>
      <%= form.text_field :phone_number %>
    </div>

    <div class="field">
      <%= form.label :website %>
      <%= form.text_field :website %>
    </div>

    <div class="create-merchant">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/merchants/edit.html.erb
<h1>Editing Merchant</h1>

<%= render 'form', merchant: @merchant %>

<div class="update-merchant">
  <%= link_to 'Show', @merchant %> |
  <%= link_to 'Back', merchants_path %>
</div>

app/views/merchants/index.html.erb
<p id="notice"><%= notice %></p>
<p id="warning"><%= warning %></p>


<h1 class="index-header">Merchants</h1>
<h6 class="filter-header">Filter by name</h6>

<%= form_tag url_for(action: :index), method: :get, class: 'form-inline' do %>
  <div class="filter-field">
    <%= text_field_tag :name_filter %>
  </div>
  <div class="button">
    <button type="submit" class="btn btn-primary">Filter</button>
  </div>
  <br>
<% end %>

<table class="table-responsive">
  <table class="table">
    <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>City</th>
      <th>Street</th>
      <th>Country code</th>
      <th>Phone number</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.email %></td>
        <td><%= merchant.name %></td>
        <td><%= merchant.city %></td>
        <td><%= merchant.street %></td>
        <td><%= merchant.country_code %></td>
        <td><%= merchant.phone_number %></td>
        <td><%= merchant.website %></td>
        <td><%= link_to 'Show', merchant %></td>
        <td><%= link_to 'Edit', edit_merchant_path(merchant) %></td>
        <td><%= link_to 'Destroy', merchant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</table>

<br>

<div class="new-merchant">
  <%= link_to 'New Merchant', new_merchant_path %>
</div>

app/views/merchants/new.html.erb
<h1>New Merchant</h1>

<%= render 'form', merchant: @merchant %>
<div class="back-link">
  <%= link_to 'Back', merchants_path %>
</div>

app/views/merchants/show.html.erb
<div class="login-actions">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Email:</strong>
    <%= @merchant.email %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @merchant.name %>
  </p>

  <p>
    <strong>City:</strong>
    <%= @merchant.city %>
  </p>

  <p>
    <strong>Street:</strong>
    <%= @merchant.street %>
  </p>

  <p>
    <strong>Country code:</strong>
    <%= @merchant.country_code %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= @merchant.phone_number %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= @merchant.website %>
  </p>


  <%= link_to 'Edit', edit_merchant_path(@merchant) %> |
  <%= link_to 'Back', merchants_path %>

</div>